package main.java;

import java.util.HashSet;

/*
 * Pentagonal numbers are generated by the formula, Pn=n(3n-1)/2. 
 * The first ten pentagonal numbers are:
 * 
 * 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
 * 
 * It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 
 * 70 - 22 = 48, is not pentagonal.
 * 
 * Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference 
 * are pentagonal and D = |Pk - Pj| is minimised; what is the value of D?
 */

public class P044 extends Problem {

	@Override
	public String solve() {
		int d = Integer.MAX_VALUE; // D from problem, D = |Pk - Pj| minimized
		
		/*
		 * Create set of pentagonals.
		 * 3000 is a complete guess as to the number of pentagonals needed:
		 */
		HashSet<Integer> pentagonals = new HashSet<Integer>();
		for (int i=1; i<3000; i++) { 
			pentagonals.add(getPentagonal(i));
		}
		
		for (Integer j : pentagonals) {
			for (Integer k : pentagonals) {
				if (!j.equals(k)) {
					/*
					 * Pk + Pj = pentagonal number, and
					 * Pk - Pj = pentagonal number
					 */
					if (pentagonals.contains(j.intValue()+k.intValue()) &&
							pentagonals.contains(k.intValue()-j.intValue())) {
						int newD = Math.abs(k.intValue()-j.intValue());
						if (newD < d) d = newD; // smaller pair found
					}
				}
			}
		}
		
		return Integer.toString(d);
	}

}
