package main.java;

/*
 * Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
 * 
 * Triangle    Tn=n(n+1)/2    1, 3, 6, 10, 15, ...
 * Pentagonal  Pn=n(3n-1)/2	  1, 5, 12, 22, 35, ...
 * Hexagonal   Hn=n(2n-1)     1, 6, 15, 28, 45, ...
 * 
 * It can be verified that T285 = P165 = H143 = 40755.
 * 
 * Find the next triangle number that is also pentagonal and hexagonal.
 */

public class P045 extends Problem {

	@Override
	public String solve() {
		long next = 0L; // answer to return
		/*
		 * T(n)      = n(n + 1)/2
		 * Substitute an odd n into T:
		 * T(2m - 1) = (2m - 1)((2m - 1) + 1)/2
		 *           = (2m - 1)2m/2
		 *           = m(2m - 1)
		 * H(n)      = n(2n - 1)
		 * Therefore, Hexagonal numbers are a subset of Triangle numbers.
		 */
		int n = 143;
		while (true) {
			n++;
			next = getHexagonal(n);
			if (isPentagonal(next)) break;
		}
		return Long.toString(next);
	}

}
